# 1. Write a Python program that takes a year as input from the user and prints whether it is a leap year or not.

In [ ]:
year = int(input("Enter a Year: "))
if (year % 4 == 0 and year % 100 != 0)  or (year % 400 == 0):
  print(f"{year} is a Leap Year")
else:
  print(f"{year} is NOT a Leap Year")

Enter a Year: 2024
2024 is a Leap Year

# 2. Write a Python program that takes three numbers as input from the user and prints the largest among them.

In [ ]:
a,b,c = map(int, input("Enter 3 numbers seperated by spaces: ").split())
if a >= b and a>= c:
  print(f"a is greatest: {a}")
elif b >= c:
   print(f"b is greatest: {b}")
else:
   print(f"c is greatest: {c}")

Enter 3 numbers seperated by spaces: 4 6 7
c is greatest: 7

# 3. Write a Python program that takes a string as input from the user and prints whether it contains only alphabetic characters or not.

In [ ]:
#simple method

s = str(input("Enter a string: "))
alpha = s.isalpha()
print(alpha)

# Best Method

s = input("Enter a string: ")
if s.isalpha():
  print(f'"{s}" contains only alphabetic characters')
else:
  print(f'"{s}" contains non-alphabetic characters')

Enter a string: 5765ythghj
False
Enter a string: rty4e5654
"rty4e5654" contains non-alphabetic characters

# 4. Write a Python program to print the square of each number from 1 to 10 using a for loop.

In [ ]:
for i in range(1, 11):
    square = i ** 2
    print(f"{i} * {i} = {square}")  # ✅ 4 spaces — runs every iteration

1 * 1 = 1
2 * 2 = 4
3 * 3 = 9
4 * 4 = 16
5 * 5 = 25
6 * 6 = 36
7 * 7 = 49
8 * 8 = 64
9 * 9 = 81
10 * 10 = 100

# 5. Write a Python program to calculate the factorial of a number entered by the user using a for loop.

In [ ]:
n = int(input("Enter a number: "))
result = 1
for i in range(1, n+1):
  result = result * i
print(f"Factorial of {n} = {result}")

Enter a number: 5
Factorial of 5 = 120

# 6. Write a Python program that declares a variable name and assigns your name to it. Then, print the value of the variable.

In [ ]:
name = 'venkatesh'
print(name)

venkates

# 7. Write a Python program that declares a variable my_list and assigns a list of your favorite colors to it. Then, print the elements of my_list.

In [ ]:
my_list = ['Green', 'Black', 'Lavender', 'Blue', 'Gold']
print("My Fav colors :", my_list)

My Fav colors : ['Green', 'Black', 'Lavender', 'Blue', 'Gold']

# 8. Write a Python program to find the sum of all elements in a list using a for loop.

In [ ]:
l = [4,5,7,8,9,55,4]
total = 0
for i in l:
    total = total + i
print(f"Sum of {l} = {total}")

Sum of [4, 5, 7, 8, 9, 55, 4] = 92

# 9. Write a Python program to count the number of vowels in a given string using a for loop.

In [ ]:
s = input("Enter a string: ")
count = 0
for i in s:
  if i in 'aeiouAEIOU':
    count = count + 1
print(f"Count of Vowels {s} = {count}")

Enter a string: Ben 10 is the best cartoon i have ever seen in the world
Count of Vowels Ben 10 is the best cartoon i have ever seen in the world = 17

# 10. Write a Python program to print the elements of a list in reverse order using a for loop.

In [ ]:
l = input("enter a list seperated by spaces :").split()
for i in range(len(l)-1, -1, -1):
  print(l[i])

enter a list seperated by spaces :7 8 9 6 5
5
6
9
8
7

# 11. Write a Python program to extract the middle element(s) from a list or tuple using slicing.

In [ ]:
e = [2, 5, 7, 6, 5, 4]

mid = len(e) // 2

if len(e) % 2 == 0:
    middle = e[mid-1 : mid+1]
else:
    middle = e[mid : mid+1]

print(f"Middle element(s) = {middle}")

Middle element(s) = [7, 6]

# 12. Write a Python program to concatenate two lists and print the result.

In [ ]:
family = ['Mani', 'Sankar', 'Saraswathi', 'Lakshmana Rao', 'Maggi', 'Mokshi']
frds = ['Ajay', 'Akash', 'Mohan', 'Gopi', 'Lali', 'Harika']

# method 1

fam_frd = family + frds
print(fam_frd)

# method 2

family.extend(frds)
print(fam_frd)

# method 3

for i in frds:
  family.append(i)
print(family)

['Mani', 'Sankar', 'Saraswathi', 'Lakshmana Rao', 'Maggi', 'Mokshi', 'Ajay', 'Akash', 'Mohan', 'Gopi', 'Lali', 'Harika']
['Mani', 'Sankar', 'Saraswathi', 'Lakshmana Rao', 'Maggi', 'Mokshi', 'Ajay', 'Akash', 'Mohan', 'Gopi', 'Lali', 'Harika']
['Mani', 'Sankar', 'Saraswathi', 'Lakshmana Rao', 'Maggi', 'Mokshi', 'Ajay', 'Akash', 'Mohan', 'Gopi', 'Lali', 'Harika', 'Ajay', 'Akash', 'Mohan', 'Gopi', 'Lali', 'Harika']

# 13. Write a Python program to find the intersection of two lists and print the result.

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

# Method 1

result = []

for i in list1:
  if i in list2:
    result.append(i)
print(f"Intersection = {result}")

# Method 2

result = list(set(list1) & set(list2))
print("Intersection", result)

Intersection = [3, 4, 5]
Intersection [3, 4, 5]

# 14. Write a Python program to find the union of two lists and print the result.

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]
result = []

for i in list1:
    result.append(i)

for i in list2:
    if i not in result:
        result.append(i)

print(f"Union = {result}")

# method 2

result = list(set(list1) | set(list2))
print(result)  # [1, 2, 3, 4, 5, 6, 7]

Union = [1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]

# 15. Write a Python program to remove duplicates from a list and print the result.

In [ ]:
l = [1, 2, 3, 2, 4, 1, 5, 3]
result = []

for i in l:
  if i not in result:
    result.append(i)
print(f"After removing duplicates = {result}")

After removing duplicates = [1, 2, 3, 4, 5]

# 16. Write a Python program to check if a given element exists in a tuple.

In [ ]:
t = (1,4,5,6,7,3,4,5)
element = int(input("Enter ELement to search: "))

#Method 1

if element in t:
  print(f"{element} exists in tuple")
else:
  print(f"{element} not found in tuple")

#Method 2

if element in t:
    print(f"{element} exists at index {t.index(element)}")

Enter ELement to search: 8
8 not found in tuple

# 17. Write a Python program to find the index of an element in a tuple.

In [ ]:
t = (1,4,5,6,7,3,4,5)
element = int(input("Enter ELement to search: "))
if element in t:
  print(f"index of element {t.index(element)}")
else:
  print(f"{element} not fount in tuple")

Enter ELement to search: 0
0 not fount in tuple

# 18. Write a Python program to convert a list to a tuple and print the result.

In [ ]:
# List to Tuple
l = [1, 4, 5, 6, 7, 3, 4, 5]
t = tuple(l)
print(f"Converted list to tuple: {t}")

Converted list to tuple: (1, 4, 5, 6, 7, 3, 4, 5)

# 19. Write a Python program to find the intersection of two sets and print the result.

In [ ]:
set1 = {1,2,3,4,5}
set2 = {3,4,5,6,7}

# Method 1

result = []

for i in set1:
  if i in set2:
    result.append(i)
print(f"Intersection = {result}")

# Method 2

result = list(set(set1) & set(set2))
print("Intersection", result)

Intersection = [3, 4, 5]
Intersection [3, 4, 5]

# 20. Write a Python program to concatenate two strings entered by the user.

In [ ]:
first_name = 'Venkatesh'
last_name = 'Ravva'

# Method 1 — + operator
full_name = first_name + ' ' + last_name

# Method 2 — f-string
full_name = f"{first_name} {last_name}"

# Method 3 — join
full_name = ' '.join([first_name, last_name])
print(full_name)

Venkatesh Ravva

In [ ]:
n = 5
for i in range(n+1):
  print("*"*i)

*
**
***
****
*****

In [ ]:
n = 5
for i in range(5,0,-1):
  print("*"*i)

*****
****
***
**
*

In [ ]:
n = 5
for i in range(1,n+1):
  print((n-i)*" " + i*"*")

    *
   **
  ***
 ****
*****

#Pandas

In [2]:
import numpy as np
import pandas as pd

data = ["Apple", "Mamgo", "Banana", "Orange"]
np.array(data)

array(['Apple', 'Mamgo', 'Banana', 'Orange'], dtype='<U6')

In [4]:
s1 = pd.Series(data)
s1

0     Apple
1     Mamgo
2    Banana
3    Orange
dtype: object

In [6]:
# custom index

s1 = pd.Series(data, index = [1, 2, 3, 4])
s1

1     Apple
2     Mamgo
3    Banana
4    Orange
dtype: object